/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Amanda
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelObservacao = new javax.swing.JLabel();
        jTextHora = new javax.swing.JTextField();
        jTextData = new javax.swing.JTextField();
        jTextValor = new javax.swing.JTextField();
        jComboServico = new javax.swing.JComboBox<>();
        jLabelHora = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelServico = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDados = new javax.swing.JTable();
        jButtonAgendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAObservacao = new javax.swing.JTextArea();
        jComboCliente = new javax.swing.JComboBox<>();
        jLabelCliente = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jLabelFundo = new javax.swing.JLabel();
        jLabelFundoGeral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agenda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservacao.setText("Observação");
        getContentPane().add(jLabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, -1, -1));
        getContentPane().add(jTextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 130, -1));
        getContentPane().add(jTextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 130, -1));
        getContentPane().add(jTextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 130, -1));

        jComboServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboServicoItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 130, -1));

        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Hora");
        getContentPane().add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data");
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor R$");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabelServico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelServico.setText("Serviço");
        getContentPane().add(jLabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setText("ID");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jTableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        jScrollPane2.setViewportView(jTableDados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 610, 110));

        jButtonAgendar.setText("Agendar");
        jButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, -1, -1));

        jTextAObservacao.setColumns(20);
        jTextAObservacao.setRows(5);
        jScrollPane1.setViewportView(jTextAObservacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 226, 230, 140));

        getContentPane().add(jComboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 130, -1));

        jLabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCliente.setText("Cliente");
        getContentPane().add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));
        getContentPane().add(jTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 130, -1));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 860, 530));

        jLabelFundoGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLabelFundoGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboServicoItemStateChanged
        this.controller.atualizaValor();
    }//GEN-LAST:event_jComboServicoItemStateChanged

    private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
        this.controller.agendar();
    }//GEN-LAST:event_jButtonAgendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JComboBox<String> jComboCliente;
    private javax.swing.JComboBox<String> jComboServico;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundoGeral;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelServico;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDados;
    private javax.swing.JTextArea jTextAObservacao;
    private javax.swing.JTextField jTextData;
    private javax.swing.JTextField jTextHora;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
        this.controller.atualizaValor();
        
    }

    public JTable getjTableDados() {
        return jTableDados;
    }

    public void setjTableDados(JTable jTableDados) {
        this.jTableDados = jTableDados;
    }

    public JComboBox<String> getjComboCliente() {
        return jComboCliente;
    }

    public void setjComboCliente(JComboBox<String> jComboCliente) {
        this.jComboCliente = jComboCliente;
    }

    public JComboBox<String> getjComboServico() {
        return jComboServico;
    }

    public void setjComboServico(JComboBox<String> jComboServico) {
        this.jComboServico = jComboServico;
    }

    public JTextField getjTextValor() {
        return jTextValor;
    }

    public void setjTextValor(JTextField jTextValor) {
        this.jTextValor = jTextValor;
    }

    public JTextArea getjTextAObservacao() {
        return jTextAObservacao;
    }

    public void setjTextAObservacao(JTextArea jTextAObservacao) {
        this.jTextAObservacao = jTextAObservacao;
    }

    public JTextField getjTextData() {
        return jTextData;
    }

    public void setjTextData(JTextField jTextData) {
        this.jTextData = jTextData;
    }

    public JTextField getjTextHora() {
        return jTextHora;
    }

    public void setjTextHora(JTextField jTextHora) {
        this.jTextHora = jTextHora;
    }

    public JTextField getjTextId() {
        return jTextId;
    }

    public void setjTextId(JTextField jTextId) {
        this.jTextId = jTextId;
    }
    
    
    
}
